import { S3Client, PutObjectCommand } from "@aws-sdk/client-s3";
import * as fs from "fs";
import { config } from "dotenv";
config({ path: "../../.env" });

async function uploadFile() {
  const s3 = new S3Client({
    region: process.env.S3_REGION || "us-east-1",
    endpoint: process.env.S3_ENDPOINT || "http://localhost:9000",
    credentials: {
      accessKeyId: process.env.S3_ACCESS_KEY || "openpims",
      secretAccessKey: process.env.S3_SECRET_KEY || "openpims123",
    },
    forcePathStyle: true,
  });

  const bucket = process.env.S3_BUCKET || "openpims";
  const fileKey = "rtg_koleno_123.jpg";
  
  // Use the image generated by generate_image
  const localFilePath = "C:\\Users\\marek\\.gemini\\antigravity-cli\\brain\\eb24fc18-3694-4708-aa79-6878a222ad9b\\dog_xray_knee_1785623292075.jpg";
  const fileContent = fs.readFileSync(localFilePath);

  console.log(`Uploading ${localFilePath} to S3 bucket ${bucket} with key ${fileKey}...`);
  await s3.send(
    new PutObjectCommand({
      Bucket: bucket,
      Key: fileKey,
      Body: fileContent,
      ContentType: "image/jpeg",
    })
  );
  console.log("File uploaded successfully.");
}

uploadFile().catch(console.error);
